#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Author: Li Yuanming
Email: yli056@e.ntu.edu.sg
Date: 1/15/2021
"""
from fastapi import APIRouter
from modelci.types.vo.model_vo import TrainerConfig
router = APIRouter()


@router.post('/{model_id}')
def submit(model_id: str, train_config: TrainerConfig):
    """
    Create a training job data object, and save it into the database. Then, submit the created training job
    (with job ID generated by database) to the training job coordinator.

    Args:
        model_id (str): Model ID for training.
        train_config (TrainerConfig): Training related parameters

    Returns:
        Submitted training job data class object.
    """
    raise NotImplementedError('Method `submit` not implemented')
