#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Author: Li Yuanming
Email: yli056@e.ntu.edu.sg
Date: 1/15/2021
"""
from typing import List

from fastapi import APIRouter

from modelci.experimental.model.model_train import TrainingJob

router = APIRouter()


@router.post('/')
def create_training_job(training_job: TrainingJob):
    """
    Create a training job data object, and save it into the database. Then, submit the created training job
    (with job ID generated by database) to the training job coordinator.

    Args:
        training_job (TrainingJob): Training job to be submitted.

    Returns:
        Submitted training job data class object.
    """
    raise NotImplementedError('Method `submit` not implemented')


@router.get('/')
def get_all_training_jobs() -> List[TrainingJob]:
    raise NotImplementedError('Method `get_all_training_jobs` not implemented.')


@router.get('/{id}')
def get_training_job(id: str) -> TrainingJob:
    """
    Get a training job.

    Args:
        id (str): Training job ID.

    Returns:
        int: Affected number of records.
    """
    raise NotImplementedError('Method `get_training_job` not implemented.')


@router.delete('/{id}')
def delete_training_job(id: str) -> int:
    """
    Delete a training job.

    Args:
        id (str): Training job ID.

    Returns:
        int: Affected number of records.
    """
    raise NotImplementedError('Method `delete_training_job` not implemented.')
