# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import service_pb2 as proto_dot_service__pb2


class PredictStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_unary(
                '/Predict/Infer',
                request_serializer=proto_dot_service__pb2.InferRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.InferResponse.FromString,
                )
        self.StreamInfer = channel.stream_stream(
                '/Predict/StreamInfer',
                request_serializer=proto_dot_service__pb2.InferRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.InferResponse.FromString,
                )


class PredictServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Infer(self, request, context):
        """Inference
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamInfer(self, request_iterator, context):
        """Stream Interface
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=proto_dot_service__pb2.InferRequest.FromString,
                    response_serializer=proto_dot_service__pb2.InferResponse.SerializeToString,
            ),
            'StreamInfer': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamInfer,
                    request_deserializer=proto_dot_service__pb2.InferRequest.FromString,
                    response_serializer=proto_dot_service__pb2.InferResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Predict', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Predict(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Predict/Infer',
            proto_dot_service__pb2.InferRequest.SerializeToString,
            proto_dot_service__pb2.InferResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamInfer(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/Predict/StreamInfer',
            proto_dot_service__pb2.InferRequest.SerializeToString,
            proto_dot_service__pb2.InferResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
